//! RFC 9457 Problem Details for HTTP APIs.
//!
//! This module provides the [`ProblemDetail`] type per
//! [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html).
//! The struct is pure data (serde-only) — framework-specific
//! `IntoResponse` implementations live in boundary crates.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// Base URI for TeoDB problem types.
const PROBLEM_TYPE_BASE: &str = "https://teodb.io/problems";

/// RFC 9457 Problem Details object.
///
/// Responses carrying this body MUST use
/// `Content-Type: application/problem+json`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProblemDetail {
    /// A URI reference that identifies the problem type.
    /// When dereferenced, it SHOULD provide human-readable documentation.
    #[serde(rename = "type")]
    pub type_uri: String,

    /// A short, human-readable summary of the problem type.
    pub title: String,

    /// The HTTP status code generated by the origin server.
    pub status: u16,

    /// A human-readable explanation specific to this occurrence.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,

    /// A URI reference that identifies the specific occurrence.
    /// Typically the request path.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,

    /// Extension: TeoDB error code for programmatic matching.
    #[serde(rename = "errorCode")]
    pub error_code: String,

    /// Extension: whether the client should retry the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,

    /// Extension: suggested retry delay in milliseconds.
    #[serde(rename = "retryAfterMs", skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<u64>,

    /// Extension: OpenTelemetry trace ID for distributed correlation.
    #[serde(rename = "traceId", skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,

    /// HATEOAS links for Richardson Maturity Model Level 3.
    #[serde(rename = "_links", default, skip_serializing_if = "HashMap::is_empty")]
    pub links: HashMap<String, Link>,
}

/// A hypermedia link per RFC 8288.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Link {
    pub href: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,

    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
}

impl Link {
    pub fn new(href: impl Into<String>) -> Self {
        Self {
            href: href.into(),
            method: None,
            title: None,
            media_type: None,
        }
    }

    pub fn with_method(mut self, method: impl Into<String>) -> Self {
        self.method = Some(method.into());
        self
    }

    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title = Some(title.into());
        self
    }
}

impl ProblemDetail {
    /// Build a `ProblemDetail` from just an HTTP status code.
    ///
    /// Derives sensible defaults for type URI, title, and error code from
    /// the status. Use the builder methods to customise.
    pub fn new(status: u16) -> Self {
        let title = default_title_for_status(status);
        let error_code = title.replace(' ', "");
        let slug = code_to_slug(&error_code);
        Self {
            type_uri: format!("{PROBLEM_TYPE_BASE}/{slug}"),
            title,
            status,
            detail: None,
            instance: None,
            error_code,
            retryable: None,
            retry_after_ms: None,
            trace_id: None,
            links: HashMap::new(),
        }
    }

    /// Build a `ProblemDetail` from an error code, HTTP status, and detail message.
    pub fn from_parts(error_code: &str, status: u16, detail: impl Into<String>) -> Self {
        let slug = code_to_slug(error_code);
        Self {
            type_uri: format!("{PROBLEM_TYPE_BASE}/{slug}"),
            title: code_to_title(error_code),
            status,
            detail: Some(detail.into()),
            instance: None,
            error_code: error_code.to_owned(),
            retryable: None,
            retry_after_ms: None,
            trace_id: None,
            links: HashMap::new(),
        }
    }

    pub fn with_title(mut self, title: impl Into<String>) -> Self {
        self.title = title.into();
        self
    }

    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.detail = Some(detail.into());
        self
    }

    pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
        self.instance = Some(instance.into());
        self
    }

    pub fn with_retryable(mut self, retryable: bool) -> Self {
        self.retryable = Some(retryable);
        self
    }

    pub fn with_retry_after_ms(mut self, ms: u64) -> Self {
        self.retry_after_ms = Some(ms);
        self
    }

    pub fn with_trace_id(mut self, trace_id: impl Into<String>) -> Self {
        self.trace_id = Some(trace_id.into());
        self
    }

    pub fn with_link(mut self, rel: impl Into<String>, link: Link) -> Self {
        self.links.insert(rel.into(), link);
        self
    }
}

/// Derive a human-readable title from an HTTP status code.
fn default_title_for_status(status: u16) -> String {
    match status {
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        405 => "Method Not Allowed",
        409 => "Conflict",
        413 => "Payload Too Large",
        415 => "Unsupported Media Type",
        422 => "Unprocessable Entity",
        429 => "Too Many Requests",
        500 => "Internal Server Error",
        502 => "Bad Gateway",
        503 => "Service Unavailable",
        _ => "Error",
    }
    .to_owned()
}

/// Convert a PascalCase error code to a kebab-case slug for the type URI.
fn code_to_slug(code: &str) -> String {
    let mut slug = String::with_capacity(code.len() + 4);
    for (i, ch) in code.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            slug.push('-');
        }
        slug.push(ch.to_ascii_lowercase());
    }
    slug
}

/// Produce a human-readable title from a PascalCase error code.
fn code_to_title(code: &str) -> String {
    let mut title = String::with_capacity(code.len() + 4);
    for (i, ch) in code.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            title.push(' ');
        }
        title.push(ch);
    }
    title
}

// TeoDBError to ProblemDetail conversion

impl crate::error::TeoDBError {
    /// Convert this error into an RFC 9457 `ProblemDetail`.
    pub fn to_problem_detail(&self) -> ProblemDetail {
        let mut pd = ProblemDetail::from_parts(self.code(), self.http_status(), self.to_string());

        if self.is_retryable() {
            pd = pd.with_retryable(true);
        }
        if let Some(ms) = self.retry_after_ms() {
            pd = pd.with_retry_after_ms(ms);
        }

        pd
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::TeoDBError;

    #[test]
    fn code_to_slug_conversion() {
        assert_eq!(code_to_slug("InvalidArgument"), "invalid-argument");
        assert_eq!(code_to_slug("NotFound"), "not-found");
        assert_eq!(code_to_slug("Internal"), "internal");
        assert_eq!(code_to_slug("RateLimited"), "rate-limited");
        assert_eq!(code_to_slug("ExternalRetryable"), "external-retryable");
    }

    #[test]
    fn code_to_title_conversion() {
        assert_eq!(code_to_title("InvalidArgument"), "Invalid Argument");
        assert_eq!(code_to_title("NotFound"), "Not Found");
    }

    #[test]
    fn problem_detail_serialization() {
        let pd = ProblemDetail::from_parts("NotFound", 404, "table 'sales.orders' not found")
            .with_instance("/v1/tables/sales/orders");

        let json = serde_json::to_value(&pd).unwrap();
        assert_eq!(json["type"], "https://teodb.io/problems/not-found");
        assert_eq!(json["title"], "Not Found");
        assert_eq!(json["status"], 404);
        assert_eq!(json["detail"], "table 'sales.orders' not found");
        assert_eq!(json["instance"], "/v1/tables/sales/orders");
        assert_eq!(json["errorCode"], "NotFound");
    }

    #[test]
    fn problem_detail_omits_null_fields() {
        let pd = ProblemDetail::from_parts("Internal", 500, "something broke");
        let json = serde_json::to_value(&pd).unwrap();

        assert!(!json.as_object().unwrap().contains_key("instance"));
        assert!(
            !json
                .as_object()
                .unwrap()
                .contains_key("retryable")
        );
        assert!(
            !json
                .as_object()
                .unwrap()
                .contains_key("retryAfterMs")
        );
        assert!(!json.as_object().unwrap().contains_key("_links"));
    }

    #[test]
    fn retryable_error_includes_retry_fields() {
        let e = TeoDBError::RateLimited { retry_after_ms: 250 };
        let pd = e.to_problem_detail();

        assert_eq!(pd.status, 429);
        assert_eq!(pd.retryable, Some(true));
        assert_eq!(pd.retry_after_ms, Some(250));
        assert_eq!(pd.type_uri, "https://teodb.io/problems/rate-limited");
    }

    #[test]
    fn non_retryable_error_no_retry_fields() {
        let e = TeoDBError::NotFound { resource: "x".into() };
        let pd = e.to_problem_detail();

        assert_eq!(pd.status, 404);
        assert_eq!(pd.retryable, None);
        assert_eq!(pd.retry_after_ms, None);
    }

    #[test]
    fn hateoas_links() {
        let pd = ProblemDetail::from_parts("NotFound", 404, "table not found")
            .with_link("self", Link::new("/v1/tables/analytics/orders").with_method("GET"));

        let json = serde_json::to_value(&pd).unwrap();
        let links = &json["_links"];
        assert_eq!(links["self"]["href"], "/v1/tables/analytics/orders");
        assert_eq!(links["self"]["method"], "GET");
    }

    #[test]
    fn roundtrip_deserialization() {
        let pd = ProblemDetail::from_parts("Conflict", 409, "snapshot conflict")
            .with_instance("/v1/tables/ns/tbl/ingest")
            .with_retryable(true);

        let json = serde_json::to_string(&pd).unwrap();
        let back: ProblemDetail = serde_json::from_str(&json).unwrap();
        assert_eq!(pd, back);
    }

    #[test]
    fn all_error_variants_produce_valid_problem_detail() {
        let errors = vec![
            TeoDBError::Config("bad".into()),
            TeoDBError::InvalidArgument {
                field: "x".into(),
                message: "bad".into(),
            },
            TeoDBError::NotFound { resource: "t".into() },
            TeoDBError::AlreadyExists { resource: "t".into() },
            TeoDBError::Conflict {
                resource: "t".into(),
                expected: "1".into(),
                actual: "2".into(),
            },
            TeoDBError::Unauthorized,
            TeoDBError::Forbidden("denied".into()),
            TeoDBError::RateLimited { retry_after_ms: 100 },
            TeoDBError::Backpressure("full".into()),
            TeoDBError::Unavailable("down".into()),
            TeoDBError::Catalog("c".into()),
            TeoDBError::Internal("i".into()),
        ];

        for e in errors {
            let pd = e.to_problem_detail();
            assert!(
                pd.type_uri
                    .starts_with("https://teodb.io/problems/")
            );
            assert!(!pd.title.is_empty());
            assert!(pd.status >= 400);
            assert!(pd.detail.is_some());
            assert!(!pd.error_code.is_empty());

            // Must serialize cleanly
            serde_json::to_string(&pd).unwrap();
        }
    }
}
