apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teodb.fullname" . }}-config
  labels:
    {{- include "teodb.labels" . | nindent 4 }}
data:
{{- if eq .Values.mode "standalone" }}
  standalone.toml: |
    {{- include "teodb.standaloneConfig" . | nindent 4 }}
{{- else }}
  data-node.toml: |
    {{- include "teodb.dataNodeConfig" . | nindent 4 }}
  control-plane.toml: |
    {{- include "teodb.controlPlaneConfig" . | nindent 4 }}
{{- end }}
