{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teodb.secretName" . }}
  labels:
    {{- include "teodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.s3AccessKey }}: {{ .Values.secret.s3AccessKey | quote }}
  {{ .Values.secret.keys.s3SecretKey }}: {{ .Values.secret.s3SecretKey | quote }}
  {{ .Values.secret.keys.clusterId }}: {{ include "teodb.clusterId" . | quote }}
  {{- if .Values.secret.adminToken }}
  {{ .Values.secret.keys.adminToken }}: {{ .Values.secret.adminToken | quote }}
  {{- end }}
{{- end }}
